# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - "./pkg/database/tableSql:/docker-entrypoint-initdb.d"
    ports:
      - 5432:5432
    environment:
#      POSTGRES_DB: bicycles
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080